### ISSUE TITLE
How to make it  work on Gitlab Page?

### ISSUE THREAD

**Issue by truonguit2010** [melvinchng/business-jekyll-theme#2]
Hi Melvinchng,

How can I make it work on Gitlab Page?

<img width="698" alt="gitlabpageerror" src="https://user-images.githubusercontent.com/4622117/46519050-2de3e500-c8a1-11e8-80e3-db72147173a4.png">

The page loaded, but it is not good.

Thank you.

**Comment by melvinchng** [comment]
Just saw this issue while I was going to my repo. It is almost 2 years late and I hoped you managed to find a solution. Meanwhile, let me put a solution here for others

If the style is not loading correctly, you may want to check the path for the imports. Check the  scripts (.js and .css) located in <head></head> to make sure it is correct.
